FROM mcr.microsoft.com/dotnet/core/sdk:2.2 AS build
WORKDIR /src
COPY ["ECommerce.Web/*.csproj", "ECommerce.Web/"]
COPY ["ECommerce.Core/*.csproj", "ECommerce.Core/"]
COPY ["ECommerce.Data/*.csproj", "ECommerce.Data/"]
RUN dotnet restore "ECommerce.Web/ECommerce.Web.csproj"
COPY . .
WORKDIR "/src/ECommerce.Web"
RUN dotnet build "ECommerce.Web.csproj" -c Release -o /app

FROM build AS publish
RUN dotnet publish "ECommerce.Web.csproj" -c Release -o /app

FROM build AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "ECommerce.Web.dll"]